### ISSUE TITLE
How to work with PPTP/L2tp/VPN/SSTAP network driver ?

### ISSUE THREAD

**Issue by wuwujia** [lonelytb/Radar-Unknown#3]
what's my ip when I play the game through online game accelerator?

**Comment by lonelytb** [comment]
It's not about IP address only, it is also related to the packet forwarding method when you play with accelerator.
As I know, most of accelerator companies use LSP. Then we have to change the way we parsing packets.
Too lazy to do that.

**Comment by wuwujia** [comment]
@lonelytb Thanks for your great work!  I know it is too complicated to capcture UDP packets from game server while we using LSP protocal proxy..
